# web 配置
web:
  server:
    port: 80         # 端口号
  servlet:
    context-path: /  # 项目根路径

spring:
  datasource:
    # druid 连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/mybatis-example
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver

